version: 'version'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: cadastro_pessoas_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'cadastro_pessoas'
    ports:
      - '3307:3306'